### PR TITLE
Handle -ck2_displayName returning nil

### PR DESCRIPTION
**Pull request by mikeabdullah**
It seems for some URLs, at least on 10.9, -getResourceValue:… returns YES and reports the display name as nil. We now treat that as an empty string so menu logic doesn't crash. The downside is you see a nameless folder in the path control.

### CODE REVIEW

**Comment by mikeabdullah** [comment]
@MrNoodle I wonder if we can make this better. Here's what I see at present when viewing a URL like `ftpes://user@example.com`:

screen shot 2014-02-25 at 10 51 58

Do you think we can display a "Home" icon instead in some fashion, with suitable name?

**Comment by MrNoodle** [comment]
I think in this case it's supposed to display the root? In that case, I think we're supposed to display the host icon and use the host name. CK2PathControl has a special case to display the host name when the display name is "/"; maybe it should also do so if it's nil or the empty string.

As for the image, that is set deeper in the code in CK2FileOperation. Displaying the server icon happens based on the number of path components. We should modify that to also do so when there are none.

**Comment by mikeabdullah** [comment]
I think you're right; have expanded the special case to cover zero-length strings too. That's a good enough implementation for my needs at the moment.

**Comment by MrNoodle** [comment]
I think you need to fix the code for the icon as well.

**Pull request merged**
