### PR TITLE
Added iOS support.

### PR DESCRIPTION
**Pull request by Coneko**
Depends on:
- [x] karelia/DAVKit#2
- [ ] karelia/CurlHandle#12
- [ ] - karelia/libssh2_sftp-Cocoa-wrapper#7
- [x] - karelia/MockServer#13

### CODE REVIEW

**Comment by Coneko** [comment]
This PR and all dependent PRs should be good to go.

I cleaned out some of the framework references, it didn't look like they were being used, since the headers weren't being imported, all tests pass and both tester apps build and run, but double-check that just to be sure.

All C libraries build from source and get detected as dependencies automatically, this way there's no need to include the binaries in the repository, which would otherwise have to include 5 architectures. The only issue left with that is that it doesn't rebuild them when the source files are changed, you have to clean manually, but it's not a big issue in my opinion: the C libraries aren't updated very often.

**Comment by Coneko** [comment]
@mikeabdullah Any update on this? If there are any issues keeping you from merging it feel free to point them out.

**Comment by mikeabdullah** [comment]
Right now the issue is me wrapping an app store submission, sorry!

**Comment by Coneko** [comment]
@mikeabdullah Still busy?

**Comment by sebromero** [comment]
Any update on this?

**Comment by danipralea** [comment]
Is there any way of actually running the project/library on an iOS device ?

**Comment by mikeabdullah** [comment]
You're welcome to try out one of the forks, but it's not something I'm actively working on at the moment

**Comment by Coneko** [comment]
I stopped updating the branch because an upstream merge wasn't likely, it's completely out of date now. Sorry.

**Comment by mikeabdullah** [comment]
My apologies, I should have been more proactive on this but iOS just isn't been enough of a priority for us yet

**Pull request closed without merging**
