### PR TITLE
Report total bytes written in progress block

### PR DESCRIPTION
**Pull request by fjaeger**

### CODE REVIEW

**Comment by mikeabdullah** [comment]
Well this is awkward. Currently WebDAV differs from the other protocols in what it reports back. I see your patch corrects this, but I believe my original intention was to go the other way, and report the number of bytes that was just transferred, rather than the total!

@MrNoodle what is your code expecting ConnectionKit to report back for upload progress? Or does it not care?

**Comment by MrNoodle** [comment]
I currently don't report progress so I don't think it's an issue for me.

**Comment by fjaeger** [comment]
Reporting the total bytes written seems more reasonable to me than reporting the latest chunk of date being transmitted

**Comment by mikeabdullah** [comment]
My instinct is that latest bytes written has a logical symmetry with reporting the data that's just arrived during a download (it's unreasonable to expect the framework to buffer the entirety of a file in memory).

I have to admit I'm coming round more to Apple's approach of:
- Report all three parameters so clients can choose what they prefer to display
- Report via a delegate method instead of block to keep the API simpler

But I still don't know. Right now the other complication is that `CKUploader` is setup to assume the bytes coming back is the amount most recently transferred.

**Comment by fjaeger** [comment]
Reporting all three is also fine with me.

May the CKUploader assumption lead to problems when uploading files via WebDAV? Currently I am encountering heavy problems with WebDAV while the other protocols are working correctly...

**Comment by mikeabdullah** [comment]
Can you elucidate what sort of problems?

WebDAV is a slightly tricky beast thanks to the nature of HTTP. The sequence _can_ go:
1. Transmit file to server
2. Receive response requesting authentication
3. Retransmit the file, this time with authentication included/updated in the headers
4. Potentially repeat 3. until auth is accepted or the user/app gives up

This can make the delegate messages a little confusing since the total bytes written will rise above the size of the raw file, and the total _expected_ byte count will adjust to match too.

**Comment by mikeabdullah** [comment]
Alright, I'm going to try changing the progress block to report all the info for now.

**Comment by fjaeger** [comment]
When trying to upload a file to my WebDAV server, I always get "(com.MattRajca.DAVKit.error-Error 409.)" ... Credentials are correct and tested via other clients.
I assume that DAVKit is not working correctly here?!

**Comment by mikeabdullah** [comment]
According to the WebDAV spec, error code 409 means you're trying to create a file in a directory that doesn't exist yet. Are you passing in `YES` for `createIntermediate` directories?

**Comment by fjaeger** [comment]
The call is the following:

``` Objective-C
[self.fileManager createFileAtURL:finalURL contents:[NSData dataWithContentsOfFile:testFilePath] withIntermediateDirectories:YES openingAttributes:nil progressBlock:nil completionHandler:^(NSError *error)
     {
...
}
```

Nothing fancy :)

**Comment by mikeabdullah** [comment]
OK, time to get your hands dirty! Can you step through `-[CK2WebDAVProtocol addCreateFileRequestForPath:…]` to figure out what's going wrong?

**Comment by fjaeger** [comment]
Alright, I did some debugging.

The problem is that the path that is being extracted in `-[CK2WebDAVProtocol pathForRequest:(NSURLRequest*)request]` does not provide URL-escaped characters. If the resulting path contains whitespaces, for example, a later call to `-[DAVRequest concatenatedURLWithPath:(NSString *)aPath]` returns `nil`

At that point, I am wondering whether FTP and SFTP have a similar problem?! But I guess the URL escaping is only crucial to the WebDAV protocol, right?

My fix looks like this:

``` objective-c
- (NSString*)pathForRequest:(NSURLRequest*)request
{
    NSString *path = [CK2WebDAVProtocol pathOfURLRelativeToHomeDirectory:request.URL];
    if (!path) path = @"/";

    return [path stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
}
```

**Comment by fjaeger** [comment]
A follow-up fix:

``` diff
--- CK2WebDAVProtocol.m
+++ CK2WebDAVProtocol.m
@@ -99,8 +99,8 @@
                 NSString *name = [[item href] lastPathComponent];
                 if (!((mask & NSDirectoryEnumerationSkipsHiddenFiles) && [name hasPrefix:@"."]))
                 {
-
-                    NSURL* url = [[davRequest concatenatedURLWithPath:[item href]] absoluteURL];
+                    NSString* path = [[item href] stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
+                    NSURL* url = [[davRequest concatenatedURLWithPath:path] absoluteURL];
                     url = [self.class URLByReplacingUserInfoInURL:url withUser:_user];

                     [CK2FileManager setTemporaryResourceValue:[item modificationDate] forKey:NSURLContentModificationDateKey inURL:url];
```

**Comment by mikeabdullah** [comment]
Thanks for the detective work! I decided the flaw lay in my implementation of `-concatentedURLWithPath:`. Fixed now. Please let me know if there's still an issue.

**Pull request merged**
